### ISSUE TITLE
¿BOM disponible?

### ISSUE THREAD

**Issue by sabas1080** [abierto-cc/fenderino#1]
Hola

¿Hay un lugar donde pueda encontrar el BOM con numero de parte de los coponentes necesarios para armar mi propio Fenderino?

Muchas gracias, excelente proyecto, saludos desde México

**Comment by MrHofflich** [comment]
Si por favor, lo he estado buscando de hace tiempo ya pero al parecer no está.

Gracias y saludos desde México!

**Comment by dcuartielles** [comment]
Hola chicos, perdón que no haya respondido antes a esta notificación. Tengo apagadas las notificaciones de github porque estoy metido en tantos repositorios que mi cuenta de mail es imposible de manejar. Así que tengo que ir mirando uno por uno.

En cualquier caso, el BOM no está colgado por error, se puede extraer directamente de las instrucciones de montaje, pero en cualquier caso en cuanto José -que mantiene el diseño- regrese de vacaciones en la semana que entra, le pediré que lo cuelgue. Es más, le voy asignar este issue ;-)

¡Estad atentos!

**Comment by GDJose** [comment]
Hola, 
Ya está disponible el BOM

**Comment by sabas1080** [comment]
Muchas gracias @GDJose
